#!/bin/bash
set -euo pipefail
umask 077
[[ $EUID -eq 0 ]] || { echo '请用 sudo bash 执行'; exit 1; }
command -v python3 >/dev/null
exec 9>/run/football-injuries-install.lock
flock -n 9 || { echo '安装正在运行'; exit 1; }
install -d -m 700 /etc/football-injuries /var/lib/football-injuries
install -d -m 755 /opt/football-injuries
if [[ ! -s /etc/football-injuries/key ]]; then
  read -r -s -p '粘贴 API-Sports 后台的 API Key（输入不显示），然后回车：' injury_key </dev/tty
  echo
  [[ -n "$injury_key" ]] || { echo '密钥为空'; exit 1; }
  printf '%s' "$injury_key" > /etc/football-injuries/key
  unset injury_key
fi
systemctl stop football-injuries.timer football-injuries.service 2>/dev/null || true
python3 - <<'CODE'
import base64,py_compile,os
from pathlib import Path
p=Path('/opt/football-injuries/collector.py')
t=p.with_suffix('.new')
t.write_bytes(base64.b64decode('aW1wb3J0IGRhdGV0aW1lIGFzIGR0CmltcG9ydCBqc29uCmltcG9ydCBvcwppbXBvcnQgc3FsaXRlMwppbXBvcnQgdXJsbGliLnJlcXVlc3QKaW1wb3J0IHVybGxpYi5lcnJvcgpmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKZnJvbSB6b25laW5mbyBpbXBvcnQgWm9uZUluZm8KClJPT1QgPSBQYXRoKCcvdmFyL2xpYi9mb290YmFsbC1pbmp1cmllcycpCmNsYXNzIE5vUmVkaXJlY3QodXJsbGliLnJlcXVlc3QuSFRUUFJlZGlyZWN0SGFuZGxlcik6CiAgICBkZWYgcmVkaXJlY3RfcmVxdWVzdChzZWxmLCAqYXJncywgKiprd2FyZ3MpOgogICAgICAgIHJldHVybiBOb25lCgpkZWYgbWFpbigpOgogICAgUk9PVC5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpCiAgICBwcmV2aW91cyA9IFJPT1QgLyAnc3RhdHVzLmpzb24nCiAgICBpZiBwcmV2aW91cy5leGlzdHMoKToKICAgICAgICBvbGQgPSBqc29uLmxvYWRzKHByZXZpb3VzLnJlYWRfdGV4dCgpKQogICAgICAgIGFnZSA9IGR0LmRhdGV0aW1lLm5vdyhkdC50aW1lem9uZS51dGMpIC0gZHQuZGF0ZXRpbWUuZnJvbWlzb2Zvcm1hdChvbGRbJ2NoZWNrZWRfYXQnXSkKICAgICAgICByZXN0cmljdGVkID0gYW55KGRbJ3N0YXRlJ10gaW4gKCdwbGFuX29yX3NlYXNvbl9yZXN0cmljdGVkJywgJ3Byb3ZpZGVyX3F1b3RhX2xpbWl0Jykgb3IgZC5nZXQoJ2h0dHBfc3RhdHVzJykgaW4gKDQwMSw0MDMpIGZvciBkIGluIG9sZC5nZXQoJ2RheXMnLCBbXSkpCiAgICAgICAgaWYgYWdlIDwgZHQudGltZWRlbHRhKGhvdXJzPTI0KSBhbmQgKHJlc3RyaWN0ZWQgb3Igb2xkLmdldCgnYWNjb3VudF9jaGVjaycpICE9ICdvaycpOgogICAgICAgICAgICBwcmludCgn5LiK5qyh6LSm5oi35oiW5p2D6ZmQ5qOA5p+l5pyq6YCa6L+H77yMMjQg5bCP5pe25ZCO5YaN5qOA5p+l77yb6K+m5oOF77yaL3Zhci9saWIvZm9vdGJhbGwtaW5qdXJpZXMvc3RhdHVzLmpzb24nKQogICAgICAgICAgICByZXR1cm4KICAgIGRiID0gc3FsaXRlMy5jb25uZWN0KFJPT1QgLyAnaW5qdXJpZXMuc3FsaXRlJykKICAgIGRiLmV4ZWN1dGUoJ0NSRUFURSBUQUJMRSBJRiBOT1QgRVhJU1RTIHJlcXVlc3RzKGF0IFRFWFQsIGVuZHBvaW50IFRFWFQpJykKICAgIGRiLmV4ZWN1dGUoJ0NSRUFURSBUQUJMRSBJRiBOT1QgRVhJU1RTIHNuYXBzaG90cyhhdCBURVhULCBkYXkgVEVYVCwgc3RhdGUgVEVYVCwgcGF5bG9hZCBURVhUKScpCiAgICBub3cgPSBkdC5kYXRldGltZS5ub3coZHQudGltZXpvbmUudXRjKQogICAgc3RhbXAgPSBub3cuaXNvZm9ybWF0KCkKICAgIHJlcG9ydCA9IHsnY2hlY2tlZF9hdCc6IHN0YW1wLCAnc291cmNlJzogJ0FQSS1Gb290YmFsbCcsICdkYXlzJzogW10sCiAgICAgICAgICAgICAgJ25vdGUnOiAn56m66L+U5Zue5LiN5Luj6KGo5YWo5ZGY5YGl5bq377yb5pWw5o2u5bCa5pyq5LiO5pys5Zyw5q+U6LWb5Yy56YWN44CCJ30KICAgIGtleSA9IFBhdGgoJy9ldGMvZm9vdGJhbGwtaW5qdXJpZXMva2V5JykucmVhZF90ZXh0KCkuc3RyaXAoKQogICAgaWYgbm90IGtleSBvciBhbnkoYy5pc3NwYWNlKCkgZm9yIGMgaW4ga2V5KToKICAgICAgICByYWlzZSBWYWx1ZUVycm9yKCflr4bpkqXkuLrnqbrmiJblkKvnqbrnmb3vvIzor7fph43mlrDphY3nva4nKQogICAgb3BlbmVyID0gdXJsbGliLnJlcXVlc3QuYnVpbGRfb3BlbmVyKHVybGxpYi5yZXF1ZXN0LlByb3h5SGFuZGxlcih7fSksIE5vUmVkaXJlY3QoKSkKICAgIGRlZiByZXF1ZXN0KGVuZHBvaW50KToKICAgICAgICAjIFJvbGxpbmcgMjQtaG91ciBjYXAgcmVtYWlucyBjb25zZXJ2YXRpdmUgYWNyb3NzIHByb3ZpZGVyIHJlc2V0IHRpbWV6b25lcy4KICAgICAgICBzaW5jZSA9IChkdC5kYXRldGltZS5ub3coZHQudGltZXpvbmUudXRjKSAtIGR0LnRpbWVkZWx0YShob3Vycz0yNCkpLmlzb2Zvcm1hdCgpCiAgICAgICAgdXNlZCA9IGRiLmV4ZWN1dGUoJ1NFTEVDVCBjb3VudCgqKSBGUk9NIHJlcXVlc3RzIFdIRVJFIGF0ID4gPycsIChzaW5jZSwpKS5mZXRjaG9uZSgpWzBdCiAgICAgICAgaWYgdXNlZCA+PSA4MDoKICAgICAgICAgICAgcmV0dXJuIHsnc3RhdGUnOiAnbG9jYWxfcXVvdGFfbGltaXQnfQogICAgICAgIGRiLmV4ZWN1dGUoJ0lOU0VSVCBJTlRPIHJlcXVlc3RzIFZBTFVFUyAoPyw/KScsIChkdC5kYXRldGltZS5ub3coZHQudGltZXpvbmUudXRjKS5pc29mb3JtYXQoKSwgZW5kcG9pbnQpKQogICAgICAgIGRiLmNvbW1pdCgpICAjIENvdW50IGZhaWxlZCByZXF1ZXN0cyBhbmQgaW50ZXJydXB0ZWQgYXR0ZW1wdHMgdG9vLgogICAgICAgIHJlcSA9IHVybGxpYi5yZXF1ZXN0LlJlcXVlc3QoJ2h0dHBzOi8vdjMuZm9vdGJhbGwuYXBpLXNwb3J0cy5pby8nICsgZW5kcG9pbnQsCiAgICAgICAgICAgICAgaGVhZGVycz17J3gtYXBpc3BvcnRzLWtleSc6IGtleSwgJ0FjY2VwdCc6ICdhcHBsaWNhdGlvbi9qc29uJ30pCiAgICAgICAgdHJ5OgogICAgICAgICAgICB3aXRoIG9wZW5lci5vcGVuKHJlcSwgdGltZW91dD0yNSkgYXMgcjoKICAgICAgICAgICAgICAgIHJhdyA9IHIucmVhZCg4XzAwMF8wMDEpCiAgICAgICAgICAgIGlmIGxlbihyYXcpID4gOF8wMDBfMDAwOgogICAgICAgICAgICAgICAgcmV0dXJuIHsnc3RhdGUnOiAncmVzcG9uc2VfdG9vX2xhcmdlJ30KICAgICAgICAgICAgZGF0YSA9IGpzb24ubG9hZHMocmF3KQogICAgICAgICAgICBpZiBub3QgaXNpbnN0YW5jZShkYXRhLCBkaWN0KToKICAgICAgICAgICAgICAgIHJldHVybiB7J3N0YXRlJzogJ2ludmFsaWRfcmVzcG9uc2UnfQogICAgICAgICAgICBpZiBkYXRhLmdldCgnZXJyb3JzJyk6CiAgICAgICAgICAgICAgICAjIERvIG5vdCBwcmludCBwcm92aWRlciBlcnJvciB0ZXh0OiBpdCBtYXkgZWNobyBhIGNyZWRlbnRpYWwuCiAgICAgICAgICAgICAgICBtc2cgPSBqc29uLmR1bXBzKGRhdGFbJ2Vycm9ycyddKS5sb3dlcigpCiAgICAgICAgICAgICAgICBzdGF0ZSA9ICdhcGlfZXJyb3InCiAgICAgICAgICAgICAgICBpZiBhbnkocyBpbiBtc2cgZm9yIHMgaW4gKCdwbGFuJywgJ3N1YnNjcmlwdGlvbicsICdzZWFzb24nLCAnYWNjZXNzJykpOgogICAgICAgICAgICAgICAgICAgIHN0YXRlID0gJ3BsYW5fb3Jfc2Vhc29uX3Jlc3RyaWN0ZWQnCiAgICAgICAgICAgICAgICBpZiBhbnkocyBpbiBtc2cgZm9yIHMgaW4gKCdsaW1pdCcsICdxdW90YScsICd0b28gbWFueScpKToKICAgICAgICAgICAgICAgICAgICBzdGF0ZSA9ICdwcm92aWRlcl9xdW90YV9saW1pdCcKICAgICAgICAgICAgICAgIHJldHVybiB7J3N0YXRlJzogc3RhdGV9CiAgICAgICAgICAgIHJldHVybiB7J3N0YXRlJzogJ29rJywgJ2RhdGEnOiBkYXRhfQogICAgICAgIGV4Y2VwdCB1cmxsaWIuZXJyb3IuSFRUUEVycm9yIGFzIGU6CiAgICAgICAgICAgIHJldHVybiB7J3N0YXRlJzogJ2h0dHBfZXJyb3InLCAnaHR0cF9zdGF0dXMnOiBlLmNvZGV9CiAgICAgICAgZXhjZXB0IChPU0Vycm9yLCBWYWx1ZUVycm9yKToKICAgICAgICAgICAgcmV0dXJuIHsnc3RhdGUnOiAnbmV0d29ya19vcl9yZXNwb25zZV9lcnJvcid9CgogICAgc3RhdHVzID0gcmVxdWVzdCgnc3RhdHVzJykKICAgIHJlcG9ydFsnYWNjb3VudF9jaGVjayddID0gc3RhdHVzWydzdGF0ZSddCiAgICBpZiBzdGF0dXNbJ3N0YXRlJ10gPT0gJ29rJzoKICAgICAgICBhY2NvdW50ID0gc3RhdHVzWydkYXRhJ10uZ2V0KCdyZXNwb25zZScsIHt9KQogICAgICAgIHJlcG9ydFsnc3Vic2NyaXB0aW9uJ10gPSB7azogYWNjb3VudC5nZXQoJ3N1YnNjcmlwdGlvbicsIHt9KS5nZXQoaykgZm9yIGsgaW4gKCdwbGFuJywgJ2FjdGl2ZScsICdlbmQnKX0KICAgICAgICByZXBvcnRbJ3Byb3ZpZGVyX3JlcXVlc3RzJ10gPSBhY2NvdW50LmdldCgncmVxdWVzdHMnLCB7fSkKICAgICAgICB0b2RheSA9IG5vdy5hc3RpbWV6b25lKFpvbmVJbmZvKCdBc2lhL1NoYW5naGFpJykpLmRhdGUoKQogICAgICAgIGZvciBkYXkgaW4gKHRvZGF5LCB0b2RheSArIGR0LnRpbWVkZWx0YShkYXlzPTEpKToKICAgICAgICAgICAgcmVzdWx0ID0gcmVxdWVzdCgnaW5qdXJpZXM/ZGF0ZT0nICsgZGF5Lmlzb2Zvcm1hdCgpICsgJyZ0aW1lem9uZT1Bc2lhJTJGU2hhbmdoYWknKQogICAgICAgICAgICBzdGF0ZSA9IHJlc3VsdFsnc3RhdGUnXQogICAgICAgICAgICByb3dzID0gcmVzdWx0LmdldCgnZGF0YScsIHt9KS5nZXQoJ3Jlc3BvbnNlJykKICAgICAgICAgICAgaWYgc3RhdGUgPT0gJ29rJzoKICAgICAgICAgICAgICAgIGlmIG5vdCBpc2luc3RhbmNlKHJvd3MsIGxpc3QpOgogICAgICAgICAgICAgICAgICAgIHN0YXRlID0gJ2ludmFsaWRfcmVzcG9uc2UnCiAgICAgICAgICAgICAgICBlbGlmIG5vdCByb3dzOgogICAgICAgICAgICAgICAgICAgIHN0YXRlID0gJ2VtcHR5X3VudmVyaWZpZWQnCiAgICAgICAgICAgICAgICBlbGlmIGFueShub3QgaXNpbnN0YW5jZSh4LCBkaWN0KSBvciBub3QgaXNpbnN0YW5jZSh4LmdldCgnZml4dHVyZScpLCBkaWN0KSBvciBub3QgaXNpbnN0YW5jZSh4LmdldCgncGxheWVyJyksIGRpY3QpIGZvciB4IGluIHJvd3MpOgogICAgICAgICAgICAgICAgICAgIHN0YXRlID0gJ2ludmFsaWRfcmVzcG9uc2UnCiAgICAgICAgICAgIHBhZ2luZyA9IHJlc3VsdC5nZXQoJ2RhdGEnLCB7fSkuZ2V0KCdwYWdpbmcnLCB7fSkKICAgICAgICAgICAgaWYgc3RhdGUgPT0gJ29rJyBhbmQgcGFnaW5nLmdldCgndG90YWwnLCAxKSA+IDE6CiAgICAgICAgICAgICAgICBzdGF0ZSA9ICdwYXJ0aWFsX3BhZ2luYXRpb24nCiAgICAgICAgICAgIGRiLmV4ZWN1dGUoJ0lOU0VSVCBJTlRPIHNuYXBzaG90cyBWQUxVRVMgKD8sPyw/LD8pJywKICAgICAgICAgICAgICAgICAgICAgICAoc3RhbXAsIGRheS5pc29mb3JtYXQoKSwgc3RhdGUsIGpzb24uZHVtcHMocmVzdWx0LmdldCgnZGF0YScsIHt9KSwgZW5zdXJlX2FzY2lpPUZhbHNlKSkpCiAgICAgICAgICAgIGRiLmNvbW1pdCgpCiAgICAgICAgICAgIHJlcG9ydFsnZGF5cyddLmFwcGVuZCh7J2RhdGUnOiBkYXkuaXNvZm9ybWF0KCksICdzdGF0ZSc6IHN0YXRlLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJ3JlY29yZHMnOiBsZW4ocm93cykgaWYgaXNpbnN0YW5jZShyb3dzLCBsaXN0KSBlbHNlIDB9KQogICAgICAgICAgICBpZiBzdGF0ZSBub3QgaW4gKCdvaycsICdlbXB0eV91bnZlcmlmaWVkJywgJ3BhcnRpYWxfcGFnaW5hdGlvbicpOgogICAgICAgICAgICAgICAgYnJlYWsKICAgIHJlcG9ydFsnbG9jYWxfcmVxdWVzdHNfMjRoJ10gPSBkYi5leGVjdXRlKCdTRUxFQ1QgY291bnQoKikgRlJPTSByZXF1ZXN0cyBXSEVSRSBhdCA+ID8nLAogICAgICAgICAgICAgKChub3ctZHQudGltZWRlbHRhKGhvdXJzPTI0KSkuaXNvZm9ybWF0KCksKSkuZmV0Y2hvbmUoKVswXQogICAgdGVtcCA9IFJPT1QgLyAnc3RhdHVzLnRtcCcKICAgIHRlbXAud3JpdGVfdGV4dChqc29uLmR1bXBzKHJlcG9ydCwgZW5zdXJlX2FzY2lpPUZhbHNlLCBpbmRlbnQ9MikpCiAgICBvcy5yZXBsYWNlKHRlbXAsIFJPT1QgLyAnc3RhdHVzLmpzb24nKQogICAgcHJpbnQoanNvbi5kdW1wcyhyZXBvcnQsIGVuc3VyZV9hc2NpaT1GYWxzZSkpCgppZiBfX25hbWVfXyA9PSAnX19tYWluX18nOgogICAgbWFpbigpCg=='))
py_compile.compile(str(t),doraise=True)
t.chmod(0o600)
os.replace(t,p)
CODE
cat > /etc/systemd/system/football-injuries.service <<'UNIT'
[Unit]
Description=API-Football injury collection and access check
After=network-online.target
[Service]
Type=oneshot
ExecStart=/usr/bin/python3 /opt/football-injuries/collector.py
TimeoutStartSec=120
UMask=0077
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=/var/lib/football-injuries
UNIT
cat > /etc/systemd/system/football-injuries.timer <<'UNIT'
[Unit]
Description=Collect injury snapshots every six hours
[Timer]
OnBootSec=5min
OnUnitActiveSec=6h
[Install]
WantedBy=timers.target
UNIT
systemctl daemon-reload
systemctl enable --now football-injuries.timer
systemctl start --no-block football-injuries.service
echo 'INJURY_INSTALL_OK：已启动后台权限检查，有权限则采集今天和明天伤停，每6小时更新。'
echo '查看结果：journalctl -u football-injuries.service -n 10 --no-pager'
echo '采集成功标志为 state: ok 且 records 大于0；安装成功不代表免费版有数据权限。'
echo '当前阶段保存独立伤停库，尚未接入看板、比赛映射或模型，不上传公开仓库。'
