#!/bin/bash
set -euo pipefail
umask 077
[[ $EUID -eq 0 ]] || { echo '请用 sudo bash 执行'; exit 1; }
exec 9>/run/football-injury-bridge-install.lock
flock -n 9 || { echo '安装正在运行'; exit 1; }
test -s /etc/football-web/access.json
test -s /etc/football-github-sync/token
test -s /opt/football-web/injury_view.py
test -s /opt/football-github-sync/sync.py
if ! /usr/bin/python3 -c 'from cryptography.hazmat.primitives.ciphers.aead import AESGCM' 2>/dev/null; then
 echo '正在安装系统加密库。'
 apt-get -o Acquire::Retries=1 -o Acquire::http::Timeout=30 -o Acquire::https::Timeout=30 update -qq
 DEBIAN_FRONTEND=noninteractive apt-get -y install python3-cryptography
fi
install -d -m 700 /opt/football-injury-bridge
systemctl stop football-injury-bridge.timer football-injury-bridge.service 2>/dev/null || true
python3 - <<'CODE'
import base64,os,py_compile,datetime
from pathlib import Path
root=Path('/opt/football-injury-bridge')
files={'injury_crypto.py': 'IiIiVmVyc2lvbmVkIGF1dGhlbnRpY2F0ZWQgZW52ZWxvcGU7IGRpc3RpbmN0IEhLREYgcHVycG9zZSBmcm9tIEFQSSBhdXRoZW50aWNhdGlvbi4iIiIKaW1wb3J0IGJhc2U2NCxqc29uLG9zCmZyb20gY3J5cHRvZ3JhcGh5Lmhhem1hdC5wcmltaXRpdmVzIGltcG9ydCBoYXNoZXMKZnJvbSBjcnlwdG9ncmFwaHkuaGF6bWF0LnByaW1pdGl2ZXMua2RmLmhrZGYgaW1wb3J0IEhLREYKZnJvbSBjcnlwdG9ncmFwaHkuaGF6bWF0LnByaW1pdGl2ZXMuY2lwaGVycy5hZWFkIGltcG9ydCBBRVNHQ00KQUFEPWInTWF0Y2hQdWxzZS9wcml2YXRlLWluanVyaWVzL3YxJwpkZWYgYjY0KGIpOnJldHVybiBiYXNlNjQuYjY0ZW5jb2RlKGIpLmRlY29kZSgnYXNjaWknKQpkZWYgdW5iNjQocyk6cmV0dXJuIGJhc2U2NC5iNjRkZWNvZGUocyx2YWxpZGF0ZT1UcnVlKQpkZWYga2V5KHNlY3JldCxzYWx0KToKIGlmIG5vdCBpc2luc3RhbmNlKHNlY3JldCxzdHIpIG9yIGxlbihzZWNyZXQpPDMyOnJhaXNlIFZhbHVlRXJyb3IoJ1JlYWQga2V5IHRvbyBzaG9ydCcpCiByZXR1cm4gSEtERihhbGdvcml0aG09aGFzaGVzLlNIQTI1NigpLGxlbmd0aD0zMixzYWx0PXNhbHQsaW5mbz1BQUQpLmRlcml2ZShzZWNyZXQuZW5jb2RlKCkpCmRlZiBlbmNyeXB0KGRhdGEsc2VjcmV0KToKIHNhbHQ9b3MudXJhbmRvbSgzMik7bm9uY2U9b3MudXJhbmRvbSgxMikKIHJhdz1qc29uLmR1bXBzKGRhdGEsZW5zdXJlX2FzY2lpPUZhbHNlLHNlcGFyYXRvcnM9KCcsJywnOicpKS5lbmNvZGUoKQogaWYgbGVuKHJhdyk+NjAwMDAwOnJhaXNlIFZhbHVlRXJyb3IoJ1BheWxvYWQgZXhjZWVkcyBsaW1pdCcpCiBjdD1BRVNHQ00oa2V5KHNlY3JldCxzYWx0KSkuZW5jcnlwdChub25jZSxyYXcsQUFEKQogcmV0dXJuIHsnZm9ybWF0JzonbWF0Y2hwdWxzZS1pbmp1cmllcy1hZXNnY20tdjEnLCdzYWx0JzpiNjQoc2FsdCksJ25vbmNlJzpiNjQobm9uY2UpLCdjaXBoZXJ0ZXh0JzpiNjQoY3QpfQpkZWYgZGVjcnlwdChlbnZlbG9wZSxzZWNyZXQpOgogaWYgZW52ZWxvcGUuZ2V0KCdmb3JtYXQnKSE9J21hdGNocHVsc2UtaW5qdXJpZXMtYWVzZ2NtLXYxJzpyYWlzZSBWYWx1ZUVycm9yKCdVbmtub3duIGZvcm1hdCcpCiBzYWx0PXVuYjY0KGVudmVsb3BlWydzYWx0J10pO25vbmNlPXVuYjY0KGVudmVsb3BlWydub25jZSddKTtjdD11bmI2NChlbnZlbG9wZVsnY2lwaGVydGV4dCddKQogaWYgbGVuKHNhbHQpIT0zMiBvciBsZW4obm9uY2UpIT0xMiBvciBsZW4oY3QpPjYwMDAxNjpyYWlzZSBWYWx1ZUVycm9yKCdJbnZhbGlkIGVudmVsb3BlJykKIHJldHVybiBqc29uLmxvYWRzKEFFU0dDTShrZXkoc2VjcmV0LHNhbHQpKS5kZWNyeXB0KG5vbmNlLGN0LEFBRCkpCg==', 'sync_injuries.py': 'aW1wb3J0IGJhc2U2NCxkYXRldGltZSBhcyBkdCxmY250bCxqc29uLHN5cyx1cmxsaWIuZXJyb3IKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCnN5cy5wYXRoLmluc2VydCgwLCcvb3B0L2Zvb3RiYWxsLWdpdGh1Yi1zeW5jJykKaW1wb3J0IHN5bmMKZnJvbSBpbmp1cnlfY3J5cHRvIGltcG9ydCBlbmNyeXB0ClJFUE89J3d1eXVucWluZzIwMTAvZm9vdGJhbGwtZGF0YScKTkFNRT0naW5qdXJpZXMtZW5jcnlwdGVkLmpzb24nCmRlZiBwaWNrKGQsa2V5cyk6cmV0dXJuIHtrOmRba10gZm9yIGsgaW4ga2V5cy5zcGxpdCgpIGlmIGsgaW4gZH0KZGVmIGV4cG9ydChkKToKIG5vdz1kdC5kYXRldGltZS5ub3coZHQudGltZXpvbmUudXRjKTtzdGFtcD1kdC5kYXRldGltZS5mcm9taXNvZm9ybWF0KGRbJ2F0J10pCiBpZiBzdGFtcC50emluZm8gaXMgTm9uZSBvciBhYnMoKG5vdy1zdGFtcCkudG90YWxfc2Vjb25kcygpKT45MDA6cmFpc2UgVmFsdWVFcnJvcignSW52YWxpZCBleHBvcnQgdGltZScpCiBpZiAnaW5qdXJ5X3N1bW1hcnknIG5vdCBpbiBkOnJhaXNlIFZhbHVlRXJyb3IoJ0luanVyeSB2aWV3IG5vdCBpbnN0YWxsZWQnKQogb3V0PXBpY2soZCwnYXQgc2FsZV9kYXRlJyk7b3V0LnVwZGF0ZShzY2hlbWE9J21hdGNocHVsc2UtcHJpdmF0ZS1pbmp1cmllcy12MScsc291cmNlPSdBUEktRm9vdGJhbGwnLG1vZGVsX3VzZXNfaW5qdXJpZXM9RmFsc2UsbWF0Y2hlcz1bXSkKIGZvciBtIGluIGRbJ21hdGNoZXMnXToKICBpdGVtPXBpY2sobSwnY2Fub25pY2FsX2lkIGhvbWUgYXdheSBsZWFndWUga2lja29mZiBjdXRvZmYnKTtpPW0uZ2V0KCdpbmp1cmllcycse30pCiAgaXRlbVsnaW5qdXJpZXMnXT1waWNrKGksJ3N0YXR1cyBzb3VyY2Ugbm90ZSBmaXh0dXJlX2lkIGNoZWNrZWRfYXQgYWdlX21pbnV0ZXMnKQogIGl0ZW1bJ2luanVyaWVzJ11bJ3BsYXllcnMnXT1bcGljayhwLCdmaXh0dXJlX2lkIHRlYW1faWQgbmFtZSB0eXBlIHJlYXNvbiBzaWRlJykgZm9yIHAgaW4gaS5nZXQoJ3BsYXllcnMnLFtdKV0KICBvdXRbJ21hdGNoZXMnXS5hcHBlbmQoaXRlbSkKIHJldHVybiBvdXQKCmRlZiBtYWluKCk6CiBsb2NrPW9wZW4oJy9ydW4vZm9vdGJhbGwtaW5qdXJ5LWJyaWRnZS5sb2NrJywndycpCiB0cnk6ZmNudGwuZmxvY2sobG9jayxmY250bC5MT0NLX0VYfGZjbnRsLkxPQ0tfTkIpCiBleGNlcHQgQmxvY2tpbmdJT0Vycm9yOnByaW50KCdJTkpVUllfQlJJREdFX0FMUkVBRFlfUlVOTklORycpO3JldHVybgogY2ZnPWpzb24ubG9hZHMoUGF0aCgnL2V0Yy9mb290YmFsbC13ZWIvYWNjZXNzLmpzb24nKS5yZWFkX3RleHQoKSkKIHRva2VuPVBhdGgoJy9ldGMvZm9vdGJhbGwtZ2l0aHViLXN5bmMvdG9rZW4nKS5yZWFkX3RleHQoKS5zdHJpcCgpCiBkPXN5bmMucmVxdWVzdCgnaHR0cDovLzEyNy4wLjAuMTo4Nzg3L2FwaS92MS9hbmFseXNpcycsY2ZnWydhcGlfa2V5J10sbG9jYWw9VHJ1ZSkKIHBheWxvYWQ9ZXhwb3J0KGQpCiByYXc9anNvbi5kdW1wcyhwYXlsb2FkLGVuc3VyZV9hc2NpaT1GYWxzZSkKIGZvciBzZWNyZXQgaW4gKHRva2VuLGNmZy5nZXQoJ2FwaV9rZXknKSxjZmcuZ2V0KCdwYXNzd29yZCcpLFBhdGgoJy9ldGMvZm9vdGJhbGwtaW5qdXJpZXMva2V5JykucmVhZF90ZXh0KCkuc3RyaXAoKSk6CiAgaWYgc2VjcmV0IGFuZCBzZWNyZXQgaW4gcmF3OnJhaXNlIFZhbHVlRXJyb3IoJ0NyZWRlbnRpYWwgZGV0ZWN0ZWQnKQogZW52ZWxvcGU9ZW5jcnlwdChwYXlsb2FkLGNmZ1snYXBpX2tleSddKQogY29udGVudD1qc29uLmR1bXBzKGVudmVsb3BlLHNlcGFyYXRvcnM9KCcsJywnOicpKS5lbmNvZGUoKQogZW50cmllcz1zeW5jLnJlcXVlc3QoJ2h0dHBzOi8vYXBpLmdpdGh1Yi5jb20vcmVwb3MvJytSRVBPKycvY29udGVudHMvP3JlZj1tYWluJyx0b2tlbikKIGlmIG5vdCBpc2luc3RhbmNlKGVudHJpZXMsbGlzdCk6cmFpc2UgVmFsdWVFcnJvcignSW52YWxpZCByZXBvc2l0b3J5IG1ldGFkYXRhJykKIGV4aXN0aW5nPVtlIGZvciBlIGluIGVudHJpZXMgaWYgZS5nZXQoJ25hbWUnKT09TkFNRV0KIGJvZHk9eydtZXNzYWdlJzonVXBkYXRlIGVuY3J5cHRlZCBpbmp1cnkgc25hcHNob3QnLCdjb250ZW50JzpiYXNlNjQuYjY0ZW5jb2RlKGNvbnRlbnQpLmRlY29kZSgpLCdicmFuY2gnOidtYWluJ30KIGlmIGV4aXN0aW5nOgogIGlmIGV4aXN0aW5nWzBdLmdldCgndHlwZScpIT0nZmlsZSc6cmFpc2UgVmFsdWVFcnJvcignVGFyZ2V0IGlzIG5vdCBhIGZpbGUnKQogIGJvZHlbJ3NoYSddPWV4aXN0aW5nWzBdWydzaGEnXQogcmVzdWx0PXN5bmMucmVxdWVzdCgnaHR0cHM6Ly9hcGkuZ2l0aHViLmNvbS9yZXBvcy8nK1JFUE8rJy9jb250ZW50cy8nK05BTUUsdG9rZW4sYm9keSkKIHByaW50KCdJTkpVUllfQlJJREdFX1NZTkNfT0sgZGF0YV9hdD0nK3N0cihkWydhdCddKSsnIG1hdGNoZXM9JytzdHIobGVuKHBheWxvYWRbJ21hdGNoZXMnXSkpKycgY29tbWl0PScrcmVzdWx0Wydjb21taXQnXVsnc2hhJ10pCmlmIF9fbmFtZV9fPT0nX19tYWluX18nOgogdHJ5Om1haW4oKQogZXhjZXB0IHVybGxpYi5lcnJvci5IVFRQRXJyb3IgYXMgZTpwcmludCgnSU5KVVJZX0JSSURHRV9GQUlMRUQgSFRUUCAnK3N0cihlLmNvZGUpKTtzeXMuZXhpdCgxKQogZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOnByaW50KCdJTkpVUllfQlJJREdFX0ZBSUxFRCAnK3R5cGUoZSkuX19uYW1lX18rJzsgY3JlZGVudGlhbHMgYW5kIGluanVyeSBkZXRhaWxzIG5vdCBsb2dnZWQnKTtzeXMuZXhpdCgxKQo=', 'read_encrypted_injuries.py': 'IiIiRGVjcnlwdCBhIGNvbm5lY3Rvci1mZXRjaGVkIGVudmVsb3BlIGxvY2FsbHkuIE5ldmVyIHVwbG9hZCB0aGUgY29ubmVjdGlvbiBmaWxlLiIiIgppbXBvcnQgYXJncGFyc2UsanNvbgpmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKZnJvbSBpbmp1cnlfY3J5cHRvIGltcG9ydCBkZWNyeXB0CnA9YXJncGFyc2UuQXJndW1lbnRQYXJzZXIoKTtwLmFkZF9hcmd1bWVudCgnZW52ZWxvcGUnKTtwLmFkZF9hcmd1bWVudCgnY29ubmVjdGlvbicpO3AuYWRkX2FyZ3VtZW50KCdvdXRwdXQnKTthPXAucGFyc2VfYXJncygpCmM9anNvbi5sb2FkcyhQYXRoKGEuY29ubmVjdGlvbikucmVhZF90ZXh0KCkpCmQ9ZGVjcnlwdChqc29uLmxvYWRzKFBhdGgoYS5lbnZlbG9wZSkucmVhZF90ZXh0KCkpLGNbJ2FwaV9rZXknXSkKUGF0aChhLm91dHB1dCkud3JpdGVfdGV4dChqc29uLmR1bXBzKGQsZW5zdXJlX2FzY2lpPUZhbHNlLGluZGVudD0yKSkKcHJpbnQoJ0RFQ1JZUFRfT0sgZGF0YV9hdD0nK3N0cihkLmdldCgnYXQnKSkrJyBtYXRjaGVzPScrc3RyKGxlbihkLmdldCgnbWF0Y2hlcycsW10pKSkpCg=='}
for name,value in files.items():
 p=root/name
 if p.exists():p.with_suffix('.backup-'+datetime.datetime.now().strftime('%Y%m%d%H%M%S')).write_bytes(p.read_bytes())
 t=p.with_suffix('.new');t.write_bytes(base64.b64decode(value));py_compile.compile(str(t),doraise=True);t.chmod(0o600);os.replace(t,p)
import sys,json
sys.path.insert(0,str(root))
from injury_crypto import encrypt,decrypt
c=json.loads(Path('/etc/football-web/access.json').read_text())
assert decrypt(encrypt({'test':True},c['api_key']),c['api_key'])=={'test':True}
print('INJURY_ENCRYPTION_CHECK_OK')
CODE
cat > /etc/systemd/system/football-injury-bridge.service <<'UNIT'
[Unit]
Description=Sync authenticated encrypted injury snapshot for private analysis
After=network-online.target football-web.service football-injury-view.service
[Service]
Type=oneshot
ExecStart=/usr/bin/python3 /opt/football-injury-bridge/sync_injuries.py
TimeoutStartSec=240
UMask=0077
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=/run
UNIT
cat > /etc/systemd/system/football-injury-bridge.timer <<'UNIT'
[Unit]
Description=Sync encrypted injury snapshot every 30 minutes
[Timer]
OnBootSec=3min
OnUnitActiveSec=30min
[Install]
WantedBy=timers.target
UNIT
systemctl daemon-reload
systemctl enable --now football-injury-bridge.timer
# Refresh only the local view, without consuming an API-Football request.
systemctl start football-injury-view.service
echo 'INJURY_BRIDGE_INSTALLED：每30分钟同步加密伤停，不额外请求 API-Football。'
echo '现在执行首次同步；网络慢时可能需要几分钟。'
if systemctl start football-injury-bridge.service; then
 journalctl -u football-injury-bridge.service -n 8 --no-pager
else
 echo '首次同步失败，查看下方日志；定时任务已安装，不要重复安装。'
 journalctl -u football-injury-bridge.service -n 10 --no-pager
 exit 1
fi
echo '请把最后的 INJURY_BRIDGE_SYNC_OK 结果告诉我，我会读取密文并验证解密。'
