#!/bin/bash
set -euo pipefail
umask 077
[[ $EUID -eq 0 ]] || { echo '请用 sudo bash'; exit 1; }
exec 9>/run/football-reliability-install.lock
flock -n 9 || { echo '更新正在进行'; exit 1; }
backup=/var/backups/football-reliability-$(date +%Y%m%d-%H%M%S)
mkdir -p "$backup"
for directory in football-audit football-web football-injury-bridge; do cp -a "/opt/$directory" "$backup/$directory"; done
units='football-quality-audit football-injury-bridge football-settlement-refresh'
for unit in $units; do
 if systemctl is-active --quiet "$unit.timer"; then echo "$unit.timer" >> "$backup/timers"; fi
 systemctl stop "$unit.timer" 2>/dev/null || true
done
resume() { if [[ -f "$backup/timers" ]]; then while read -r timer; do systemctl start "$timer" || true; done < "$backup/timers"; fi; }
rollback() { for directory in football-audit football-web football-injury-bridge; do cp -a "$backup/$directory/." "/opt/$directory/"; done; systemctl restart football-web.service || true; resume; echo "安装失败，已恢复代码：$backup"; }
trap rollback ERR
for unit in $units; do
 for attempt in $(seq 1 90); do
  state=$(systemctl show "$unit.service" -p ActiveState --value 2>/dev/null || true)
  [[ "$state" != active && "$state" != activating ]] && break
  if [[ $attempt -eq 90 ]]; then resume; echo '任务仍在运行，请稍后重试'; exit 1; fi
  sleep 2
 done
done
python3 - <<'FILES'
from pathlib import Path
import base64,os,grp,py_compile
for name,data in {'/opt/football-audit/reliability.py': 'IiIiUHJvc3BlY3RpdmUgcGFpcmVkIGV2YWx1YXRpb247IG5vIHJldHJvc3BlY3RpdmUgZW5yb2xtZW50IG9yIG1vZGVsIHByb21vdGlvbi4iIiIKaW1wb3J0IGpzb24sbWF0aCxzcWxpdGUzLGhhc2hsaWIKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCmZyb20gZGF0ZXRpbWUgaW1wb3J0IGRhdGV0aW1lLHRpbWVkZWx0YSx0aW1lem9uZQpST09UPVBhdGgoJy9vcHQvZm9vdGJhbGwnKQpLRVlTPSgnaG9tZScsJ2RyYXcnLCdhd2F5JykKZGVmIHN0YW1wKHYpOgogZD12IGlmIGlzaW5zdGFuY2UodixkYXRldGltZSkgZWxzZSBkYXRldGltZS5mcm9taXNvZm9ybWF0KHN0cih2KS5yZXBsYWNlKCdaJywnKzAwOjAwJykpCiBpZiBkLnR6aW5mbyBpcyBOb25lOnJhaXNlIFZhbHVlRXJyb3IoJ3RpbWV6b25lIHJlcXVpcmVkJykKIHJldHVybiBkCgpkZWYgc3VtbWFyeShlbnRyaWVzKToKIHBhaXJlZD1bZSBmb3IgZSBpbiBlbnRyaWVzIGlmIGUuZ2V0KCdyZXN1bHQnKV0KIHZhbHM9W10KIGZvciBlIGluIHBhaXJlZDoKICByPWVbJ3Jlc3VsdCddO3k9J2hvbWUnIGlmIHJbJ2hvbWVfZ29hbHMnXT5yWydhd2F5X2dvYWxzJ10gZWxzZSAnYXdheScgaWYgclsnYXdheV9nb2FscyddPnJbJ2hvbWVfZ29hbHMnXSBlbHNlICdkcmF3JwogIHZhbHMuYXBwZW5kKFstbWF0aC5sb2cobWF4KGVba11beV0sMWUtMTIpKSBmb3IgayBpbiAoJ2luY3VtYmVudCcsJ2NhbmRpZGF0ZScsJ21hcmtldCcpXSkKIHJldHVybiB7J2Vucm9sbGVkJzpsZW4oZW50cmllcyksJ3NldHRsZWQnOmxlbih2YWxzKSwnaW5jdW1iZW50X2xvZ19sb3NzJzpzdW0odlswXSBmb3IgdiBpbiB2YWxzKS9sZW4odmFscykgaWYgdmFscyBlbHNlIE5vbmUsJ2NhbmRpZGF0ZV9sb2dfbG9zcyc6c3VtKHZbMV0gZm9yIHYgaW4gdmFscykvbGVuKHZhbHMpIGlmIHZhbHMgZWxzZSBOb25lLCdtYXJrZXRfbG9nX2xvc3MnOnN1bSh2WzJdIGZvciB2IGluIHZhbHMpL2xlbih2YWxzKSBpZiB2YWxzIGVsc2UgTm9uZSwnc3RhdHVzJzonY29sbGVjdGluZ19mdXR1cmVfZXZpZGVuY2UnLCdhdXRvX3Byb21vdGlvbic6RmFsc2UsJ25vdGUnOiflkIzlnLrjgIHlkIzliLvlm7rlrprpooTmtYvvvJvlubPlnYfmjZ/lpLHotorkvY7otorlpb3jgILmoLfmnKzlsJHml7bkuI3og73liKTmlq3kvJjliqPvvIzkuI3oh6rliqjmm7/mjaLmqKHlnovjgIInfQoKZGVmIGV4dGVuZChvdXQsZGIsZ2FtZXMsbm93KToKIGltcG9ydCBtb2RlbCBhcyBlbmdpbmUKIGFjdGl2ZT1qc29uLmxvYWRzKChST09ULydtb2RlbHMvYWN0aXZlLmpzb24nKS5yZWFkX3RleHQoKSkKIHRyYWluaW5nPWpzb24ubG9hZHMoKFJPT1QvJ3JlcG9ydHMvdHJhaW5pbmcuanNvbicpLnJlYWRfdGV4dCgpKQogdmVyc2lvbj10cmFpbmluZy5nZXQoJ3ZlcnNpb24nLCcnKQogaWYgbm90IHZlcnNpb24gb3IgJy8nIGluIHZlcnNpb246cmFpc2UgVmFsdWVFcnJvcignaW52YWxpZCBjYW5kaWRhdGUgdmVyc2lvbicpCiBjYW5kaWRhdGU9anNvbi5sb2FkcygoUk9PVC8nbW9kZWxzJy92ZXJzaW9uLydtb2RlbC5qc29uJykucmVhZF90ZXh0KCkpCiBsZWRnZXI9c3FsaXRlMy5jb25uZWN0KFJPT1QvJ3JlcG9ydHMvcGFpcmVkLWV2YWx1YXRpb24uc3FsaXRlJykKIGxlZGdlci5leGVjdXRlKCdDUkVBVEUgVEFCTEUgSUYgTk9UIEVYSVNUUyBwYWlycyhwYWlyX2lkIFRFWFQgUFJJTUFSWSBLRVksIHBheWxvYWQgVEVYVCBOT1QgTlVMTCknKQogbGVkZ2VyLmV4ZWN1dGUoJ0NSRUFURSBUQUJMRSBJRiBOT1QgRVhJU1RTIG9ic2VydmF0aW9ucyhwYWlyX2lkIFRFWFQsZXZlbnRfa2V5IFRFWFQscGF5bG9hZCBURVhUIE5PVCBOVUxMLFBSSU1BUlkgS0VZKHBhaXJfaWQsZXZlbnRfa2V5KSknKQogaGFzaGVzPVtoYXNobGliLnNoYTI1Nihqc29uLmR1bXBzKG0sc29ydF9rZXlzPVRydWUpLmVuY29kZSgpKS5oZXhkaWdlc3QoKSBmb3IgbSBpbiAoYWN0aXZlLGNhbmRpZGF0ZSldCiBwYWlyX2lkPSc6Jy5qb2luKGhhc2hlcykKIGxlZGdlci5leGVjdXRlKCdJTlNFUlQgT1IgSUdOT1JFIElOVE8gcGFpcnMgVkFMVUVTICg/LD8pJywocGFpcl9pZCxqc29uLmR1bXBzKHsnY3JlYXRlZF9hdCc6bm93Lmlzb2Zvcm1hdCgpLCdpbmN1bWJlbnQnOmFjdGl2ZVsndmVyc2lvbiddLCdjYW5kaWRhdGUnOmNhbmRpZGF0ZVsndmVyc2lvbiddLCdoYXNoZXMnOmhhc2hlc30pKSkKIHBhaXI9anNvbi5sb2FkcyhsZWRnZXIuZXhlY3V0ZSgnU0VMRUNUIHBheWxvYWQgRlJPTSBwYWlycyBXSEVSRSBwYWlyX2lkPT8nLChwYWlyX2lkLCkpLmZldGNob25lKClbMF0pCiBpZiBhY3RpdmVbJ3ZlcnNpb24nXSE9Y2FuZGlkYXRlWyd2ZXJzaW9uJ106CiAgZm9yIGcgaW4gZ2FtZXM6CiAgIHRyeToKICAgIGlmIG5vdCAoNzIwMDw9KGdbJ2N1dG9mZiddLW5vdykudG90YWxfc2Vjb25kcygpPD0xMDgwMCBhbmQgMDw9KG5vdy1nWydsYXN0X3NlZW4nXSkudG90YWxfc2Vjb25kcygpPD05MDApOmNvbnRpbnVlCiAgICBpZiBhbnkoc3RhbXAobVsndHJhaW5lZF9hdCddKT49bm93IG9yIHN0YW1wKG1bJ3RyYWluX2VuZCddKT49Z1sna2lja29mZiddIGZvciBtIGluIChhY3RpdmUsY2FuZGlkYXRlKSk6Y29udGludWUKICAgIG9kZHM9Z1snb2RkcyddO2ludj17azoxL2Zsb2F0KG9kZHNba10pIGZvciBrIGluIEtFWVN9CiAgICBpZiBub3QgYWxsKG1hdGguaXNmaW5pdGUodikgYW5kIDA8djwxIGZvciB2IGluIGludi52YWx1ZXMoKSk6Y29udGludWUKICAgIHA9eydhdCc6bm93Lmlzb2Zvcm1hdCgpLCdraWNrb2ZmJzpnWydraWNrb2ZmJ10uaXNvZm9ybWF0KCksJ2hvbWUnOmdbJ2hvbWUnXSwnYXdheSc6Z1snYXdheSddLCdtYXJrZXQnOntrOnYvc3VtKGludi52YWx1ZXMoKSkgZm9yIGssdiBpbiBpbnYuaXRlbXMoKX19CiAgICBmb3Iga2V5LG0gaW4gWygnaW5jdW1iZW50JyxhY3RpdmUpLCgnY2FuZGlkYXRlJyxjYW5kaWRhdGUpXToKICAgICBkPWVuZ2luZS5kaXN0cmlidXRpb24oKmVuZ2luZS5yYXRlcyhtLGcpKTtwW2tleV09e2s6ZFtrXSBmb3IgayBpbiBLRVlTfQogICAgbGVkZ2VyLmV4ZWN1dGUoJ0lOU0VSVCBPUiBJR05PUkUgSU5UTyBvYnNlcnZhdGlvbnMgVkFMVUVTKD8sPyw/KScsKHBhaXJfaWQsZ1snY2Fub25pY2FsX2lkJ10sanNvbi5kdW1wcyhwKSkpCiAgIGV4Y2VwdCAoVmFsdWVFcnJvcixUeXBlRXJyb3IsS2V5RXJyb3IpOmNvbnRpbnVlCiBsZWRnZXIuY29tbWl0KCkKIGVudHJpZXM9W10KIGZvciBrZXkscmF3IGluIGxlZGdlci5leGVjdXRlKCdTRUxFQ1QgZXZlbnRfa2V5LHBheWxvYWQgRlJPTSBvYnNlcnZhdGlvbnMgV0hFUkUgcGFpcl9pZD0/JywocGFpcl9pZCwpKToKICBwPWpzb24ubG9hZHMocmF3KQogIHI9ZGIuZXhlY3V0ZSgnU0VMRUNUIGhvbWVfZ29hbHMsYXdheV9nb2FscyxwdWJsaXNoZWRfYXQgRlJPTSBjYW5vbmljYWxfcmVzdWx0cyBXSEVSRSBjYW5vbmljYWxfaWQ9JXMgQU5EIHB1Ymxpc2hlZF9hdDw9bm93KCknLChrZXksKSkuZmV0Y2hhbGwoKQogIGlmIGxlbihyKT09MSBhbmQgc3RhbXAoclswXVsncHVibGlzaGVkX2F0J10pPj1zdGFtcChwWydraWNrb2ZmJ10pIGFuZCBub3c+PXN0YW1wKHBbJ2tpY2tvZmYnXSkrdGltZWRlbHRhKGhvdXJzPTIpOnBbJ3Jlc3VsdCddPXJbMF0KICBlbnRyaWVzLmFwcGVuZChwKQogb3V0WydwYWlyZWRfZXZhbHVhdGlvbiddPXsqKnN1bW1hcnkoZW50cmllcyksKipwYWlyfQogbGVkZ2VyLmNsb3NlKCkKIHN0YXR1cz17fTtkZXRhaWxzPVtdCiBmb3IgaXRlbSBpbiBvdXRbJ3BhcGVyJ11bJ3JlY2VudF9yZWNvcmRzJ106CiAgaWYgaXRlbS5nZXQoJ3Jlc3VsdCcpOnN0YXRlPSdzZXR0bGVkJwogIGVsaWYgbm93PHN0YW1wKGl0ZW1bJ2tpY2tvZmYnXSkrdGltZWRlbHRhKGhvdXJzPTMpOnN0YXRlPSd3YWl0aW5nX2Zvcl9tYXRjaCcKICBlbHNlOgogICBmb3VuZD1kYi5leGVjdXRlKCdTRUxFQ1Qgc2FsZV9kYXRlIEZST00gY2Fub25pY2FsX21hdGNoZXMgV0hFUkUgY2Fub25pY2FsX2lkPSVzJywoaXRlbVsnY2Fub25pY2FsX2lkJ10sKSkuZmV0Y2hhbGwoKQogICBzdGF0ZT0nd2FpdGluZ19mb3Jfc291cmNlX3Jlc3VsdCcgaWYgZm91bmQgZWxzZSAnY2Fub25pY2FsX21hcHBpbmdfbWlzc2luZycKICBzdGF0dXNbc3RhdGVdPXN0YXR1cy5nZXQoc3RhdGUsMCkrMQogIGlmIHN0YXRlIG5vdCBpbiAoJ3NldHRsZWQnLCd3YWl0aW5nX2Zvcl9tYXRjaCcpOmRldGFpbHMuYXBwZW5kKHsnY2Fub25pY2FsX2lkJzppdGVtWydjYW5vbmljYWxfaWQnXSwnaG9tZSc6aXRlbVsnaG9tZSddLCdhd2F5JzppdGVtWydhd2F5J10sJ3N0YXRlJzpzdGF0ZX0pCiBvdXRbJ3NldHRsZW1lbnRfY2hlY2snXT17J2NvdW50cyc6c3RhdHVzLCdzY29wZSc6J3JlY2VudCBwYXBlciByZWNvcmRzLCBhdCBtb3N0IDEwMCcsJ3BlbmRpbmcnOmRldGFpbHMsJ25vdGUnOifmnKrnu5PnrpfkuI3kvJrorqHkuLrovpPmiJbotaLvvJvmnaXmupDlm57mn6Xmr4/lsI/ml7bmnIDlpJoz5Liq5pel5pyf77yM5LiN6LCD55So5Lyk5YGcQVBJ44CCJ30K', '/opt/football-audit/refresh_results.py': 'IiIiUmVmcmVzaCByZXN1bHQgZGF0ZXMgZm9yIG92ZXJkdWUgZW5yb2xsZWQgb2JzZXJ2YXRpb25zLCBib3VuZGVkIGFuZCBsb2NrZWQuIiIiCmltcG9ydCBzeXMsanNvbixzcWxpdGUzCmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aApmcm9tIGRhdGV0aW1lIGltcG9ydCBkYXRldGltZSx0aW1lem9uZSx0aW1lZGVsdGEKc3lzLnBhdGguaW5zZXJ0KDAsJy9vcHQvZm9vdGJhbGwvYXBwJykKaW1wb3J0IGZvb3RiYWxsCmZyb20gZGVkdXAgaW1wb3J0IHJlZnJlc2gKUk9PVD1QYXRoKCcvb3B0L2Zvb3RiYWxsJykKZGVmIG1haW4oKToKIHBhdGg9Uk9PVC8ncmVwb3J0cy9wYXBlci1hdWRpdC5zcWxpdGUnCiBpZiBub3QgcGF0aC5leGlzdHMoKTpyZXR1cm4KIGxlZGdlcj1zcWxpdGUzLmNvbm5lY3QoJ2ZpbGU6JytzdHIocGF0aCkrJz9tb2RlPXJvJyx1cmk9VHJ1ZSkKIHBlbmRpbmc9bGVkZ2VyLmV4ZWN1dGUoJ1NFTEVDVCBvLmV2ZW50X2tleSxvLnBheWxvYWQgRlJPTSBvYnNlcnZhdGlvbnMgbyBMRUZUIEpPSU4gc2V0dGxlbWVudHMgcyBVU0lORyhldmVudF9rZXkpIFdIRVJFIHMuZXZlbnRfa2V5IElTIE5VTEwnKS5mZXRjaGFsbCgpO2xlZGdlci5jbG9zZSgpCiBub3c9ZGF0ZXRpbWUubm93KHRpbWV6b25lLnV0Yyk7cmVwb3J0PVJPT1QvJ3JlcG9ydHMvc2V0dGxlbWVudC1yZWZyZXNoLmpzb24nCiBwcmV2aW91cz1qc29uLmxvYWRzKHJlcG9ydC5yZWFkX3RleHQoKSkgaWYgcmVwb3J0LmV4aXN0cygpIGVsc2Uge30KIHdpdGggZm9vdGJhbGwuY29ubmVjdCgpIGFzIGRiOgogIGlmIG5vdCBkYi5leGVjdXRlKCdTRUxFQ1QgcGdfdHJ5X2Fkdmlzb3J5X2xvY2soNzAyMjAyNjA5MTApJykuZmV0Y2hvbmUoKVswXTpwcmludCgnU0VUVExFTUVOVF9SRUZSRVNIX0JVU1knKTtyZXR1cm4KICBkYXlzPXNldCgpCiAgZm9yIGtleSxyYXcgaW4gcGVuZGluZzoKICAgcD1qc29uLmxvYWRzKHJhdykKICAgaWYgbm93LWRhdGV0aW1lLmZyb21pc29mb3JtYXQocFsna2lja29mZiddKTx0aW1lZGVsdGEoaG91cnM9Myk6Y29udGludWUKICAgZm9yIHJvdyBpbiBkYi5leGVjdXRlKCdTRUxFQ1Qgc2FsZV9kYXRlIEZST00gY2Fub25pY2FsX21hdGNoZXMgV0hFUkUgY2Fub25pY2FsX2lkPSVzJywoa2V5LCkpOmRheXMuYWRkKHN0cihyb3dbMF0pKQogIHN0YW1wcz1wcmV2aW91cy5nZXQoJ2NoZWNrZWRfZGF0ZXMnLHt9KTt0YXJnZXRzPXNvcnRlZChkYXlzLGtleT1sYW1iZGEgeDpzdGFtcHMuZ2V0KHgsJycpKVs6M107ZmFpbGVkPVtdCiAgZm9yIGRheSBpbiB0YXJnZXRzOgogICBvaz1mb290YmFsbC5jb2xsZWN0X29uZShkYiwnc291cmNlX2FfaGlzdG9yeScsZGF5KQogICBzdGFtcHNbZGF5XT1ub3cuaXNvZm9ybWF0KCkKICAgaWYgbm90IG9rOmZhaWxlZC5hcHBlbmQoZGF5KTticmVhawogIGlmIHRhcmdldHM6cmVmcmVzaChkYikKICBmb290YmFsbC5hdG9taWMocmVwb3J0LHsnYXQnOm5vdy5pc29mb3JtYXQoKSwnY2hlY2tlZF9kYXRlcyc6c3RhbXBzLCdhdHRlbXB0ZWQnOnRhcmdldHMsJ2ZhaWxlZCc6ZmFpbGVkLCdwZW5kaW5nX2RhdGVzJzpsZW4oZGF5cyl9KQogIHByaW50KCdTRVRUTEVNRU5UX1JFRlJFU0hfT0sgYXR0ZW1wdGVkPScrc3RyKGxlbih0YXJnZXRzKSkrJyBmYWlsZWQ9JytzdHIobGVuKGZhaWxlZCkpKQppZiBfX25hbWVfXz09J19fbWFpbl9fJzptYWluKCkK', '/opt/football-web/selection_view.py': 'ZnJvbSBkYXRldGltZSBpbXBvcnQgZGF0ZXRpbWUsdGltZXpvbmUKaW1wb3J0IG1hdGgKS0VZUz0oJ2hvbWUnLCdkcmF3JywnYXdheScpCmRlZiBmcmVzaCh2LG5vdyxzZWNvbmRzKToKIHRyeTpyZXR1cm4gMDw9KG5vdy1kYXRldGltZS5mcm9taXNvZm9ybWF0KHN0cih2KS5yZXBsYWNlKCdaJywnKzAwOjAwJykpKS50b3RhbF9zZWNvbmRzKCk8PXNlY29uZHMKIGV4Y2VwdCAoVmFsdWVFcnJvcixUeXBlRXJyb3IpOnJldHVybiBGYWxzZQoKZGVmIGFzc2VzcyhtLG5vdz1Ob25lKToKIG5vdz1ub3cgb3IgZGF0ZXRpbWUubm93KHRpbWV6b25lLnV0Yyk7cmVhc29ucz1bXTtwPW0uZ2V0KCdwcmVkaWN0aW9uJyx7fSk7cHJvYnM9cC5nZXQoJ3Byb2JhYmlsaXRpZXMnLHt9KQogaWYgcC5nZXQoJ3N0YXR1cycpIT0nY3VycmVudCcgb3Igbm90IGZyZXNoKHAuZ2V0KCdwcmVkaWN0ZWRfYXQnKSxub3csOTAwKTpyZWFzb25zLmFwcGVuZCgn6aKE5rWL57y65aSx5oiW6LaF6L+HMTXliIbpkp8nKQogaWYgcC5nZXQoJ3Vuc2Vlbl90ZWFtJykgaXMgbm90IEZhbHNlOnJlYXNvbnMuYXBwZW5kKCfnkIPpmJ/orq3nu4Popobnm5bmnKrnoa7orqQnKQogdHJ5OgogIGlmIGRhdGV0aW1lLmZyb21pc29mb3JtYXQoc3RyKG1bJ2N1dG9mZiddKS5yZXBsYWNlKCdaJywnKzAwOjAwJykpPD1ub3c6cmVhc29ucy5hcHBlbmQoJ+W3sue7j+WBnOWUricpCiBleGNlcHQgKEtleUVycm9yLFZhbHVlRXJyb3IsVHlwZUVycm9yKTpyZWFzb25zLmFwcGVuZCgn5YGc5ZSu5pe26Ze05pyq56Gu6K6kJykKIG1hcmtldHM9W10KIGZvciBzIGluIG0uZ2V0KCdvZGRzX3NvdXJjZXMnLFtdKToKICBpZiBub3QgZnJlc2gocy5nZXQoJ2xhc3Rfc2VlbicpLG5vdyw5MDApOmNvbnRpbnVlCiAgdHJ5OgogICBpbnY9e2s6MS9mbG9hdChzWydtYXJrZXRzJ11bJ3NwZiddWydvZGRzJ11ba10pIGZvciBrIGluIEtFWVN9CiAgIGlmIGFsbChtYXRoLmlzZmluaXRlKHYpIGFuZCAwPHY8MSBmb3IgdiBpbiBpbnYudmFsdWVzKCkpOm1hcmtldHMuYXBwZW5kKHtrOnYvc3VtKGludi52YWx1ZXMoKSkgZm9yIGssdiBpbiBpbnYuaXRlbXMoKX0pCiAgZXhjZXB0IChLZXlFcnJvcixWYWx1ZUVycm9yLFR5cGVFcnJvcixaZXJvRGl2aXNpb25FcnJvcik6cGFzcwogaWYgbm90IG1hcmtldHM6cmVhc29ucy5hcHBlbmQoJ+e8uuWwkTE15YiG6ZKf5YaF6LWU546HJykKIHRyeToKICBpZiBub3QgYWxsKG1hdGguaXNmaW5pdGUocHJvYnNba10pIGFuZCAwPD1wcm9ic1trXTw9MSBmb3IgayBpbiBLRVlTKSBvciBhYnMoc3VtKHByb2JzW2tdIGZvciBrIGluIEtFWVMpLTEpPjFlLTU6cmFpc2UgVmFsdWVFcnJvcigpCiAgaWYgbWFya2V0cyBhbmQgbWF4KGFicyhwcm9ic1trXS1iW2tdKSBmb3IgYiBpbiBtYXJrZXRzIGZvciBrIGluIEtFWVMpPj0uMjA6cmVhc29ucy5hcHBlbmQoJ+aooeWei+S4jui1lOeOh+WIhuatp+i+vuWIsDIw5Liq55m+5YiG54K5JykKIGV4Y2VwdCAoS2V5RXJyb3IsVmFsdWVFcnJvcixUeXBlRXJyb3IpOnJlYXNvbnMuYXBwZW5kKCfmqKHlnovmpoLnjofml6DmlYgnKQogaW5qdXJpZXM9bS5nZXQoJ2luanVyaWVzJyx7fSkKIGlmIGluanVyaWVzLmdldCgnc3RhdHVzJykhPSdtYXRjaGVkX3JlY29yZHMnIG9yIG5vdCBmcmVzaChpbmp1cmllcy5nZXQoJ2NoZWNrZWRfYXQnKSxub3csNzIwMCk6cmVhc29ucy5hcHBlbmQoJ+S8pOWBnOe8uuWkseaIluafpeivoui2hei/hzLlsI/ml7YnKQogaWYgYW55KCflhrLnqoEnIGluIHN0cih4LmdldCgndHlwZScsJycpKSBvciAn5Yay56qBJyBpbiBzdHIoeC5nZXQoJ3JlYXNvbicsJycpKSBmb3IgeCBpbiBpbmp1cmllcy5nZXQoJ3BsYXllcnMnLFtdKSk6cmVhc29ucy5hcHBlbmQoJ+S8pOWBnOeKtuaAgeWtmOWcqOWGsueqgScpCiByZWFzb25zLmFwcGVuZCgn6aaW5Y+R5LiO5Y+M5pa55Lyk5YGc5a6M5pW05oCn5LuN6ZyA6LWb5YmN5qC45a6eJykKIHJldHVybiB7J3N0YXR1cyc6J2hvbGQnLCdyZWFzb25zJzpsaXN0KGRpY3QuZnJvbWtleXMocmVhc29ucykpLCdhdXRvbWF0aWNfY29tYmluYXRpb24nOkZhbHNlLCdub3RlJzon5LuF5Li66LWE5paZ5qOA5p+l77yM5LiN5Luj6KGo6IOc546H5oiW55uI5Yip5LyY5Yq/77yb5YWB6K645b2T5aSp5rKh5pyJ5o6o6I2Q44CCJ30K'}.items():
 p=Path(name);t=p.with_suffix('.new');t.write_bytes(base64.b64decode(data));py_compile.compile(str(t),doraise=True);t.chmod(0o640);os.chown(t,0,grp.getgrnam('footballweb' if 'football-web/' in name else 'football').gr_gid);os.replace(t,p)
FILES
python3 - <<'PATCH'
from pathlib import Path
import os,py_compile

def patch(path,marker,anchor,replacement):
 p=Path(path);s=p.read_text()
 if marker in s:return
 if s.count(anchor)!=1:raise RuntimeError('Unsupported installed version: '+path)
 s=s.replace(anchor,replacement);st=p.stat();t=p.with_suffix('.new');t.write_text(s)
 if p.suffix=='.py':py_compile.compile(str(t),doraise=True)
 os.chmod(t,st.st_mode);os.chown(t,st.st_uid,st.st_gid);os.replace(t,p)
patch('/opt/football-audit/audit.py','# reliability-v1',"p=ROOT/'reports/quality-audit.json';",'''# reliability-v1
try:
 from reliability import extend
 with psycopg.connect('dbname=football user=football host=/var/run/postgresql',row_factory=dict_row,options='-c search_path=football_v1 -c statement_timeout=20000 -c default_transaction_read_only=on') as checkdb:
  extend(out,checkdb,games,NOW)
except Exception as e:
 out['paired_evaluation']={'status':'failed','error_type':type(e).__name__,'auto_promotion':False}
p=ROOT/'reports/quality-audit.json';''')
patch('/opt/football-web/web.py','# reliability-view-v1','  return result\n',"  # reliability-view-v1\n  from selection_view import assess\n  for match in rows:match['analysis_screen']=assess(match)\n  return result\n")
patch('/opt/football-injury-bridge/sync_injuries.py','# reliability-export-v1',"  out['matches'].append(item)","  # reliability-export-v1\n  item['analysis_screen']=m.get('analysis_screen',{})\n  out['matches'].append(item)")
patch('/opt/football-web/app.js','// reliability-screen-v1','for(const s of m.odds_sources)',"""// reliability-screen-v1
const sc=m.analysis_screen; if(sc){const box=node('div',undefined,'odds');box.append(node('strong','分析筛选：暂不自动推荐'));for(const reason of sc.reasons||[])box.append(node('p',reason));card.append(box);}
for(const s of m.odds_sources)""")

PATCH
systemctl restart football-web.service
systemctl start football-quality-audit.service
python3 - <<'VERIFY'
import json
r=json.load(open('/opt/football/reports/quality-audit.json'))
assert r['paired_evaluation']['status']=='collecting_future_evidence', '新旧模型比较检查失败'
assert 'settlement_check' in r
print('RELIABILITY_AUDIT_OK paired='+str(r['paired_evaluation']['enrolled']))
import urllib.request,time
c=json.load(open('/etc/football-web/access.json'))
op=urllib.request.build_opener(urllib.request.ProxyHandler({}))
for attempt in range(8):
 try:
  req=urllib.request.Request('http://127.0.0.1:8787/ui-api/data',headers={'Authorization':'Bearer '+c['api_key']})
  with op.open(req,timeout=30) as response:data=json.load(response)
  assert all('analysis_screen' in m for m in data['matches'])
  print('RELIABILITY_VIEW_OK matches='+str(len(data['matches'])))
  break
 except Exception:
  if attempt==7:raise SystemExit('看板接口验证失败')
  time.sleep(1)
VERIFY
cat > /etc/systemd/system/football-settlement-refresh.service <<'UNIT'
[Unit]
Description=Refresh overdue paper result dates
[Service]
Type=oneshot
User=football
Group=football
ExecStart=/opt/football/.venv/bin/python /opt/football-audit/refresh_results.py
TimeoutStartSec=180
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/opt/football/reports /opt/football/data
UNIT
cat > /etc/systemd/system/football-settlement-refresh.timer <<'UNIT'
[Timer]
OnBootSec=5min
OnUnitActiveSec=1h
[Install]
WantedBy=timers.target
UNIT
systemctl daemon-reload
resume
systemctl enable --now football-settlement-refresh.timer
trap - ERR
systemctl start --no-block football-settlement-refresh.service football-github-sync.service football-injury-bridge.service
echo 'RELIABILITY_UPDATE_OK：赛前双模型留档、未结算诊断、分析筛选已安装。'
echo '赛果每小时最多回查3个日期，不消耗伤停API额度；新模型比较需积累之后的比赛，不自动替换。'
echo "备份：$backup"
